name: Continuous integration

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: "Create ENV file"
        run: |
          touch tests.env
          echo OPENSUBS_USERNAME="${{ secrets.OPENSUBS_USERNAME }}" >> tests.env
          echo OPENSUBS_PASSWORD="${{ secrets.OPENSUBS_PASSWORD }}" >> tests.env
          echo OPENSUBS_APIKEY="${{ secrets.OPENSUBS_APIKEY }}" >> tests.env
      - run: pnpm install
      - run: pnpm test